language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -U -r requirements.txt
  - npm install -g phantomjs
# command to run tests
script:
  - cd tests/
  - python -m unittest discover
